name: Java CI with Maven

on:
  push:
    branches:
      - main  # attiva il workflow solo per il branch main
  pull_request:
    branches:
      - main  # attiva il workflow anche per le pull request

jobs:
  build:
    runs-on: ubuntu-latest  # usa una macchina virtuale Ubuntu per eseguire il job
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # fa il checkout del codice dal repository

    - name: Set up JDK 21.0.6
      uses: actions/setup-java@v2
      with:
        java-version: '21.0.6'  # imposta la versione di Java che desideri usare

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install  # esegue il build con Maven

